# This file was generated by GoReleaser. DO NOT EDIT.
class Glab < Formula
  desc "An open source GitLab CLI tool"
  homepage "https://github.com/profclems/glab"
  version "1.11.0-pre2"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/profclems/glab/releases/download/v1.11.0-pre2/glab_1.11.0-pre2_macOS_amd64.tar.gz"
    sha256 "1f74856f03f94d3945900e9f983af3b56c8b79c2a7ee1ca05bcbba896d28945a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/profclems/glab/releases/download/v1.11.0-pre2/glab_1.11.0-pre2_Linux_amd64.tar.gz"
      sha256 "9384b0320a25db7b1f8135f82673428334acd70aefa735214f90e11fe45f7770"
    end
  end
  
  depends_on "git"

  def install
    bin.install "bin/glab"
  end

  test do
    system "#{bin}/glab version"
  end
end
