# This file was generated by GoReleaser. DO NOT EDIT.
class Glab < Formula
  desc "An open source GitLab CLI tool"
  homepage "https://github.com/profclems/glab"
  version "1.11.1"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/profclems/glab/releases/download/v1.11.1/glab_1.11.1_macOS_amd64.tar.gz"
    sha256 "61aae53888a3d5731fe9e375c3f379de2feb991e5f3cf6d21e80b37a42a2a93e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/profclems/glab/releases/download/v1.11.1/glab_1.11.1_Linux_amd64.tar.gz"
      sha256 "c8a189ce1a6aedd5654be1601ea02ec6436445b07d8ad1e4bc34dc8883a43ea7"
    end
  end
  
  depends_on "git"

  def install
    bin.install "bin/glab"
  end

  test do
    system "#{bin}/glab version"
  end
end
