# This file was generated by GoReleaser. DO NOT EDIT.
class Tfa < Formula
  desc "Super cool two-factor authentication command line app"
  homepage "https://github.com/profclems/tfa"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/profclems/tfa/releases/download/v0.1.0/tfa_0.1.0_macOS_amd64.tar.gz"
    sha256 "56fd3f2f774e0e5c0bc88e36411202525b8fc10fb00b7c7e57ddcba43a80650f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "http://github.com/profclems/tfa/releases/download/v0.1.0/tfa_0.1.0_Linux_amd64.tar.gz"
    sha256 "b071681554a0ef53fcf46688f897c4a07944d3e787a2cf9a2d55d51d2ab929ee"
  end

  depends_on "git"

  def install
    bin.install "bin/tfa"
  end

  test do
    system "#{bin}/tfa version"
  end
end
