# This file was generated by GoReleaser. DO NOT EDIT.
class Tfa < Formula
  desc "Super cool two-factor authentication command line app"
  homepage "https://github.com/profclems/tfa"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/profclems/tfa/releases/download/v0.1.0/tfa_0.1.0_macOS_amd64.tar.gz"
    sha256 "1298bbbcaf58aee00316899888ffae92cfe371ed4bdbb57f915000cb232cb39d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "http://github.com/profclems/tfa/releases/download/v0.1.0/tfa_0.1.0_Linux_amd64.tar.gz"
    sha256 "6f962a2acd3e558fe10bd46cedace1178e0d80430bff1d28e794d23468a3ad71"
  end

  depends_on "git"

  def install
    bin.install "bin/tfa"
  end

  test do
    system "#{bin}/tfa version"
  end
end
